### ISSUE TITLE
Execution of git-commit-id-plugin failed: Bare Repository has neither a working tree nor index

### ISSUE THREAD

**Issue by ericeberry** [ktoso/maven-git-commit-id-plugin#105]
I get the following exception when I try to use any version of git-commit-id-plugin after version 2.1.4.  Is there something I have configured incorrectly?

This is my configuration:
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>${git-commit-id-plugin.version}</version>
                <configuration>
                    <failOnNoGitDirectory>false</failOnNoGitDirectory>
                    <failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>
                    <skipPoms>false</skipPoms>
                    <verbose>false</verbose>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision (default) on project com.ccadllc.ees.messaging: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision failed: Bare Repository has neither a working tree, nor an index -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision (default) on project com.ccadllc.ees.messaging: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision failed: Bare Repository has neither a working tree, nor an index
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.9:revision failed: Bare Repository has neither a working tree, nor an index
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
	at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1075)
	at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:87)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:87)
	at pl.project13.jgit.DescribeCommand.findDirtyState(DescribeCommand.java:377)
	at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:313)
	at pl.project13.maven.git.GitCommitIdMojo.putGitDescribe(GitCommitIdMojo.java:509)
	at pl.project13.maven.git.GitCommitIdMojo.maybePutGitDescribe(GitCommitIdMojo.java:502)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:448)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:307)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	... 20 more

**Comment by TheSnoozer** [comment]
Hi,
first of all thanks for reporting this issue.
It's been a while since this issue is on the market and I just wanted to check if someone could reproduce it.
It seems that at least some problems reported back in the days resolved itself, so I think it's ok to check whether there are some problems still open.

Thanks,

**Comment by TheSnoozer** [comment]
Due to inactivity and the latest comments I would assume that is got solved somehow. If it occurs again, please open a new issue.

Thanks for reporting :-)
