### ISSUE TITLE
Please release 2.1.14

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#193]
As discussed in https://github.com/ktoso/maven-git-commit-id-plugin/pull/192
I think a release would be nice to have.
We have collected a lot of version upgrades and some NPE fixes (a total of 59 commits):
https://github.com/ktoso/maven-git-commit-id-plugin/compare/v2.1.13...master

Maybe it's worth to put https://github.com/ktoso/maven-git-commit-id-plugin/issues/191 into the Release...

**Comment by ktoso** [comment]
Excellent, I'm on it :-) Thanks so much for triaging and merging all these tickets for this release!

**Comment by ktoso** [comment]
Yeah I'll look into the logging thing actually... makes sense. Then I'll release. // @TheSnoozer

**Comment by TheSnoozer** [comment]
Thanks Konrad!
I tried to fix the logging issue a couple of days ago, but I had barely time to work in it....
At least I found some custom implementations of the slf4j:
https://code.google.com/p/slf4j-maven-plugin-log/
http://slf4j.jcabi.com/

However I wasn't able to get them connected to the simpleLogger that takes the args for ``-Dorg.slf4j.simpleLogger.defaultLogLevel=warn``

**Comment by ktoso** [comment]
The impl looks good, sorry that I didn't manage to impl it before you :-)
Rolling the release now!

**Comment by ktoso** [comment]
Some tests fail for me locally... I'll need to fix those before releasing I think. I'll ping you once that's solved:

```
  testCompareSubrepoInChild(pl.project13.maven.git.NativeAndJGitProviderTest)  Time elapsed: 2.9 sec  <<< FAILURE!
    org.junit.ComparisonFailure: Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
    	at org.junit.Assert.assertEquals(Assert.java:115)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.verifyNativeAndJGit(NativeAndJGitProviderTest.java:126)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.testCompareSubrepoInChild(NativeAndJGitProviderTest.java:89)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

    testCompareSubrepoInRoot(pl.project13.maven.git.NativeAndJGitProviderTest)  Time elapsed: 3.168 sec  <<< FAILURE!
    org.junit.ComparisonFailure: Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
    	at org.junit.Assert.assertEquals(Assert.java:115)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.verifyNativeAndJGit(NativeAndJGitProviderTest.java:126)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.testCompareSubrepoInRoot(NativeAndJGitProviderTest.java:76)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

    testCompareBasic(pl.project13.maven.git.NativeAndJGitProviderTest)  Time elapsed: 2.651 sec  <<< FAILURE!
    org.junit.ComparisonFailure: Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
    	at org.junit.Assert.assertEquals(Assert.java:115)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.verifyNativeAndJGit(NativeAndJGitProviderTest.java:126)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.testCompareBasic(NativeAndJGitProviderTest.java:63)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

    testCompareISO8601Time(pl.project13.maven.git.NativeAndJGitProviderTest)  Time elapsed: 2.695 sec  <<< FAILURE!
    org.junit.ComparisonFailure: Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
    	at org.junit.Assert.assertEquals(Assert.java:115)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.verifyNativeAndJGit(NativeAndJGitProviderTest.java:126)
    	at pl.project13.maven.git.NativeAndJGitProviderTest.testCompareISO8601Time(NativeAndJGitProviderTest.java:100)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


    Results :

    Failed tests:   testCompareSubrepoInChild(pl.project13.maven.git.NativeAndJGitProviderTest): Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
      testCompareSubrepoInRoot(pl.project13.maven.git.NativeAndJGitProviderTest): Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
      testCompareBasic(pl.project13.maven.git.NativeAndJGitProviderTest): Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>
      testCompareISO8601Time(pl.project13.maven.git.NativeAndJGitProviderTest): Key difference for key: 'git.commit.message.full' expected:<... special characters [�����].> but was:<... special characters [äöüàñ].>

    Tests run: 105, Failures: 4, Errors: 0, Skipped: 1
```

**Comment by TheSnoozer** [comment]
Hi @ktoso ,
this looks like some sort of wierdo encoding problem....
Can you check what will be outputted by ``$ mvn clean package -X | grep "platform encoding"``

Also maybe changing the Assert Equals in LN127 to the following
``
assertEquals("Key difference for key: '" + key + "'", Charset.forName("UTF-8").encode(jgitProps.getProperty(key)), Charset.forName("UTF-8").encode(nativeProps.getProperty(key)));``    

If this somehow fixes the problem then me may have an encoding problem somewhere :-(

**Comment by ktoso** [comment]
Released!

**Comment by TheSnoozer** [comment]
Awsome! Thanks :-)
How could you fix the encoding problem?

**Comment by ktoso** [comment]
TBH I just ran it from my linux box, mac was doing weird things with console output. I don't think it's a bug in the plugin - my console is crooked somehow

**Comment by TheSnoozer** [comment]
on mac it's a feature ;-)

**Comment by ktoso** [comment]
(-;

**Comment by TheSnoozer** [comment]
@ktoso 
somehow it seems that the 2.1.14 is not available on maven.org

see:
```
https://search.maven.org/#search|gav|1|g%3A%22pl.project13.maven%22%20AND%20a%3A%22git-commit-id-plugin%22
```

**Comment by ktoso** [comment]
Argh, multitasking! :-)
Done - I had forgotten to click the release button on sonatype.  It's on its way to central now.

**Comment by ktoso** [comment]
And it's on central http://search.maven.org/#browse%7C1779525593

**Comment by ktoso** [comment]
Thanks for the check @TheSnoozer!

**Comment by TheSnoozer** [comment]
Hahha :-)
No worries, it's also now online on serach.maven.org.

Thanks!
