### ISSUE TITLE
java.lang.NullPointerException at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)

### ISSUE THREAD

**Issue by TheSnoozer** [ktoso/maven-git-commit-id-plugin#341]
### Expected Behavior

No NPE's

### Current Behavior

``java.lang.NullPointerException at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)``
while building with ``mvn -T 4 clean package -Dmaven.test.skip=true``

### Steps to Reproduce (for bugs only)

```xml
<plugin>
            <groupId>pl.project13.maven</groupId>
            <artifactId>git-commit-id-plugin</artifactId>
            <version>${project.version}</version>
            <!-- optional to change the phases of the individual mojo's -->
            <executions>
              <execution>
                <id>get-the-git-infos</id>
                <goals>
                  <goal>revision</goal>
                </goals>
              </execution>
              <execution>
                <id>validate-the-git-infos</id>
                <goals>
                  <goal>validateRevision</goal>
                </goals>
                <phase>package</phase>
             </execution>
            </executions>
            <configuration>
              <verbose>false</verbose>
              <skip>false</skip>
              <prefix>git</prefix>
              <dotGitDirectory>/tmp/linux/.git</dotGitDirectory>
              <generateGitPropertiesFile>true</generateGitPropertiesFile>
              <generateGitPropertiesFilename>target/testing.properties</generateGitPropertiesFilename>
              <dateFormat>yyyy-MM-dd'T'HH:mm:ssZ</dateFormat>
              <dateFormatTimeZone>GMT-08:00</dateFormatTimeZone>
              <useNativeGit>false</useNativeGit>
              <abbrevLength>7</abbrevLength>
              <format>properties</format>
              <injectAllReactorProjects>true</injectAllReactorProjects>
              <gitDescribe>
                <skip>false</skip>
                <always>false</always>
                <abbrev>7</abbrev>
                <match>*</match>
                <dirty>-DEVEL</dirty>
                <forceLongFormat>false</forceLongFormat>
              </gitDescribe>
              <excludeProperties>
                <excludeProperty>git.commit.*</excludeProperty>
                <excludeProperty>git.remote.origin.url</excludeProperty>
              </excludeProperties>
              <replacementProperties>
                <replacementProperty>
                  <property>git.branch</property>
                  <propertyOutputSuffix>something</propertyOutputSuffix>
                  <token>^([^\/]*)\/([^\/]*)$</token>
                  <value>$1-$2</value>
                  <transformationRules>
                    <transformationRule>
                      <apply>BEFORE</apply>
                      <action>UPPER_CASE</action>
                    </transformationRule>
                  </transformationRules>
                </replacementProperty>
              </replacementProperties>
              <failOnNoGitDirectory>false</failOnNoGitDirectory>
              <failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>
              <!-- used in validateRevision -->
              <validationProperties>
                <validationProperty>
                  <name>validating project version</name>
                  <value>${project.version}</value>
                  <!-- <shouldMatchTo>^[0-9\.]*$</shouldMatchTo> -->
                  <shouldMatchTo><![CDATA[^.*(?<!-SNAPSHOT)$]]></shouldMatchTo>
                </validationProperty>
                <validationProperty>
                  <name>validating git dirty</name>
                  <value>${git.dirty}</value>
                  <shouldMatchTo>false</shouldMatchTo>
                </validationProperty>
              </validationProperties>
              <validationShouldFailIfNoMatch>true</validationShouldFailIfNoMatch>
            </configuration>
          </plugin>
```

```
cd /tmp
git clone https://github.com/torvalds/linux.git
mvn -T 4 clean package -Dmaven.test.skip=true
```

```
[INFO] Failed while parsing [Ref[refs/tags/v2.6.11=5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8c]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.11-tree] [null], points at [tree c39ae07f393806ccf406ef966e9a15afc43cc36a ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.11-tree=5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8c]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.12] [null], points at [commit 9ee1c939d1cb936b1f98e8d81aeffab57bae46ab 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.12=26791a8bcf0e6d33f43aef7682bdb555236d56de]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.12-rc2] [null], points at [commit 1da177e4c3f41524e886b7f1b8a0c1fc7321cac2 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.12-rc2=9e734775f7c22d2f89943ad6c745571f1930105f]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.12-rc3] [null], points at [commit a2755a80f40e5794ddc20e00f781af9d6320fafb 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.12-rc3=0397236d43e48e821cce5bbe6a80a1a56bb7cc3a]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.12-rc4] [null], points at [commit 88d7bd8cb9eb8d64bf7997600b0d64f7834047c5 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.12-rc4=ebb5573ea8beaf000d4833735f3e53acb9af844c]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.12-rc5] [null], points at [commit 2a24ab628aa7b190be32f63dfb6d96f3fb61580a 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.12-rc5=06f6d9e2f140466eeb41e494e14167f90210f89d]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.12-rc6] [null], points at [commit 7cef5677ef3a8084f2588ce0a129dc95d65161f6 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.12-rc6=701d7ecec3e0c6b4ab9bb824fd2b34be4da63b7e]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.13] [PersonIdent[Linus Torvalds, torvalds@g5.osdl.org, Sun Aug 28 16:42:28 2005 -0700]], points at [commit 02b3e4e2d71b6058ec11cc01c72ac651eb3ded2b 0 ------] 
[INFO] Resolved tag [v2.6.13-rc1] [null], points at [commit 4c91aedb75d1b87deccf16d58f67fb46402d7d44 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.13-rc1=733ad933f62e82ebc92fed988c7f0795e64dea62]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.13-rc2] [null], points at [commit a18bcb7450840f07a772a45229de4811d930f461 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.13-rc2=c521cb0f10ef2bf28a18e1cc8adf378ccbbe5a19]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Resolved tag [v2.6.13-rc3] [null], points at [commit c32511e2718618f0b53479eb36e07439aa363a74 0 ------] 
[INFO] Failed while parsing [Ref[refs/tags/v2.6.13-rc3=a339981ec18d304f9efeb9ccf01b1f04302edf32]] -- 
java.lang.NullPointerException
	at pl.project13.jgit.dummy.DatedRevTag.<init>(DatedRevTag.java:32)
	at pl.project13.jgit.JGitCommon.getCommitIdsToTags(JGitCommon.java:174)
	at pl.project13.jgit.JGitCommon.getClosestTagAsMap(JGitCommon.java:108)
	at pl.project13.jgit.JGitCommon.getClosestTagCommitCount(JGitCommon.java:93)
	at pl.project13.maven.git.JGitProvider.getClosestTagCommitCount(JGitProvider.java:201)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:136)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:534)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:501)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:385)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment (for bugs only)

```
java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/share/maven-3.5.0
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-96-generic", arch: "amd64", family: "unix"
```

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

``/bin/bash``

``mvn -T 4 clean package -Dmaven.test.skip=true``

**Comment by TheSnoozer** [comment]
Potentially the tags in questions had been created before git was cool.
The NPE gets thrown inside the https://github.com/ktoso/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/jgit/dummy/DatedRevTag.java#L32
Without further testing I would imagine that ``tag.getTaggerIdent().getWhen()`` yields the NPE. 
This theory would align with the releases that don't have a release date (https://github.com/torvalds/linux/releases?after=v2.6.13-rc6)
