### ISSUE TITLE
NumberFormatException when running under openJ9

### ISSUE THREAD

**Issue by angu16** [ktoso/maven-git-commit-id-plugin#397]
jamm-0.3.0.jar is an implicit dependency for my project. When starting under linux x64 with openj9 (jdk8u192-b12) the project crashes with the following exception:

Caused by: java.lang.NumberFormatException: For input string: "openj9-0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.github.jamm.MemoryLayoutSpecification.getEffectiveMemoryLayoutSpecification(MemoryLayoutSpecification.java:190)
	at org.github.jamm.MemoryLayoutSpecification.<clinit>(MemoryLayoutSpecification.java:31)

**Comment by angu16** [comment]
Wrong project, sorry
