### ISSUE TITLE
Error when some tag in local repo: "Unable to find commits until some tag: Did not find any commits until some tag"

### ISSUE THREAD

**Issue by abnuk** [ktoso/maven-git-commit-id-plugin#61]
When we have a tag in local repo the following exception is thrown:
"Unable to find commits until some tag: Did not find any commits until some tag"

**Comment by TheSnoozer** [comment]
Hi, this issue is on the market for quite a long time and I wanted to check if there is any issue unresolved yet ar at least a workaround suggested.
I bumped into this mysqlf, but this is issue can also occour when using the native git binary (see my last comment). 
To avoid this we either can use the ``git describe --always`` or the ``failOnUnableToExtractRepoInfo``switch.
So I'm not sure if this resolves everybodys issue or if there is still a bug inside the git-commit-id plugin.

Thanks,

**Comment by vbauer** [comment]
I have the same problem with version 2.1.9:

```java
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision (default) on project xss-taglib: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision failed: Unable to find commits until some tag: Did not find any commits until some tag -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision (default) on project xss-taglib: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision failed: Unable to find commits until some tag
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.5:revision failed: Unable to find commits until some tag
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.RuntimeException: Unable to find commits until some tag
	at pl.project13.jgit.DescribeCommand.findCommitsUntilSomeTag(DescribeCommand.java:430)
	at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:328)
	at pl.project13.maven.git.GitCommitIdMojo.putGitDescribe(GitCommitIdMojo.java:456)
	at pl.project13.maven.git.GitCommitIdMojo.maybePutGitDescribe(GitCommitIdMojo.java:449)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:395)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:269)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.RuntimeException: Did not find any commits until some tag
	at pl.project13.jgit.DescribeCommand.findCommitsUntilSomeTag(DescribeCommand.java:428)
```

**Comment by TheSnoozer** [comment]
Hi @vbauer could you post your configuration of the plugin?
Does the suggested workarounds do not help here?

Thanks,

**Comment by vbauer** [comment]
Configuration of the plugin:
```java
                <plugin>
                    <groupId>pl.project13.maven</groupId>
                    <artifactId>git-commit-id-plugin</artifactId>
                    <version>${git-commit-id-plugin.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <prefix>git</prefix>
                        <verbose>true</verbose>
                        <dateFormat>yyyy-MM-dd-HH-mm-ss</dateFormat>
                    </configuration>
                </plugin>
```

I haven't tried to use workaround, just wanted to provide some additional information. For now, I can build project in Intellij IDEA (instead of console) and it is fine for me.

**Comment by mdern** [comment]
This is not vbauer's email.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by vbauer** [comment]
I've just tried to use version 2.2.0 and it works fine (sorry, I haven't seen it before).

**Comment by TheSnoozer** [comment]
Thanks for the feedback :-)
I'll close this finally since it seems to work fine and there are multiple workarounds available :-)

@mdern, Everybody will receive an eMail who subscribed to this issue :-)

**Comment by gaetanlebrun** [comment]
I've tried version 2.2.2 and in my in my case JGit is not able to honor `git describe --always` command.

I solved the issue by turning on the native git support feature:

    <useNativeGit>true</useNativeGit>

**Comment by TheSnoozer** [comment]
Please do open a new issue for this and paste in a full config of your plugin.
Also it would help if you include what you expect and what you get....

**Comment by ggb667** [comment]
git tag -l | xargs git tag -d 
Will delete the tags and fix the problem.

**Comment by TheSnoozer** [comment]
I don't think deleting tags in your repository is the "fix". It's likely either a problem or a problem with what you ask from git, or potentially even still a problem in the plugin.

As outlined above -- totential ways of avoiding the issue
1) use the native git implementation
```xml
<useNativeGit>true</useNativeGit>
```

2) always describe:
```xml
<gitDescribe>
    <skip>false</skip>
    <always>true</always>
</gitDescribe>
```

if that doesn't solve it please open a new ticket ideally with a repository where this issue can be reproduced.
