### ISSUE TITLE
git-commit-id-plugin seems to hang when called from jenkins (maybe invalid?)

### ISSUE THREAD

**Issue by kumaravel-jayakumar** [ktoso/maven-git-commit-id-plugin#90]
I use git-commit-id-plugin in the validate phase and it seems to run well in my local maven. After I check in my code we have a fusion job that checks out the project and runs a build in it. But the job never seems to end. The job runs a sonar plugin as the final step which in turn calls the cobertura plugin. 

It simply hangs at.. (taken from logs)
[INFO] Preparing cobertura:cobertura
[INFO] [git-commit-id:revision {execution: default}]
[info]   

The plugin hangs for ever. I configured git-commit-id-plugin to run in <phase>validate</phase> phase.

**Comment by TheSnoozer** [comment]
Hi @kumaravel-jayakumar,
it's been a while since this issue is on the market.
Do you have any further input?

**Comment by TheSnoozer** [comment]
Unfortunately due the lack of feedback here I see no other choice to close this as "Won't Fix" and will put it on the "graveyard".
If the problem is still present please let us know or try to play around with the native git implementation.

Thanks,
S.

**Comment by plopezlpz** [comment]
I have experienced this issue. The problem happens when the last commit message is too long (has too many lines, 44 lines in my case), this can happen when there are many merge conflicts.

The stack trace looks like this:
```
"main" #1 prio=5 os_prio=0 tid=0x0000000001f4f800 nid=0x20e8 runnable [0x00000000020ed000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
        at java.lang.ProcessImpl.waitFor(ProcessImpl.java:449)
        at pl.project13.maven.git.NativeGitProvider$JavaProcessRunner.run(NativeGitProvider.java:380)
        at pl.project13.maven.git.NativeGitProvider.runQuietGitCommand(NativeGitProvider.java:293)
        at pl.project13.maven.git.NativeGitProvider.getCommitMessageFull(NativeGitProvider.java:198)
        at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:116)
        at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithNativeGit(GitCommitIdMojo.java:573)
        at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:556)
        at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:376)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
Debugging this I found out the problem was when trying to run this git command: `git log -1 --pretty=format:%B`
Running it on the terminal I see when there are too many lines the command does not finish instead waits for user input.
I'm using version pl.project13.maven:git-commit-id-plugin:2.1.15

# Workaround 

Check this is in fact the issue, running `git log -1 --pretty=format:%B` and verify the console does not return and waits for user input. If this is the case just create a new dummy commit with a small commit message.

**Comment by ktoso** [comment]
I don't think that's the reason.
Console apps know if it's an interactive shell or not, and will *not* wait for user input when called from a non-interactive shell - like we do in this plugin.

**Comment by ktoso** [comment]
To confirm my statement:

```
$ scala
scala> import sys.process._
scala> "git log --pretty=format:%B".!
// ... prints a lot of stuff and completes
```

**Comment by plopezlpz** [comment]
maybe it is something with my git configuration, anyway the workaround worked for me

**Comment by liyangeva999** [comment]
Got the exact same issue, the previous commit message contains too many lines, a new commit with less lines of commit messages fix the problem.

**Comment by TheSnoozer** [comment]
@liyangeva999 could you provide more information about the environment and the git version used? configuration etc.?
